[package]
name = "casgen"
version = "0.1.0"
edition = "2021"
description = "A way to generate cas12 6-plex CRISPR sequences"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.9", features = ["derive"] }
